# Site settings
title: David Tan
description: David Tan | Full-stack web developer and data science enthusiast.
keywords: Web development, data science, code, coding, programming, tutorials, learning, general assembly,
author: David Tan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "davified.github.io" # the base hostname & protocol for your site
